baseURL = "https://bvebarcelona.cat/"
title = "BVE Barcelona"
theme = "kozmo-dark"
DefaultContentLanguage = "ca"
removePathAccents = true

[params]
  name = "BVE Barcelona"
  copyright = "BVE Barcelona"
  logoimage = "images/logo.png"
  attribution = "true"
  custom_css = "css/site.css"

[params.custom]
  faviconPNG = "favicon.png"

[blackfriday]
  fractions = false

[permalinks]
  noticies = "/:section/:year/:month/:day/:title/"


[languages]
[languages.ca]
baseURL = "https://bvebarcelona.cat/"
languageName = "Català"
weight = 1
description = "El lloc web oficial del Metro de Barcelona per a openBVE"


[languages.es]
baseURL = "https://es.bvebarcelona.cat/"
languageName = "Castellano"
weight = 2
description = "El sitio web oficial del Metro de Barcelona para openBVE"
    

[languages.en]
baseURL = "https://en.bvebarcelona.cat/"
languageName = "English"
weight = 3
description = "The official website of the Barcelona Metro for openBVE"




[[languages.ca.menu.main]]
    name = "RSS"
    weight = 7
    url = "/noticies/index.xml"
[[languages.es.menu.main]]
    name = "RSS"
    weight = 7
    url = "/noticias/index.xml"
[[languages.en.menu.main]]
    name = "RSS"
    weight = 7
    url = "/news/index.xml"
